# Generated by Django 4.1.1 on 2022-09-13 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=250, null=True)),
                ("city", models.CharField(max_length=100, null=True)),
                (
                    "country",
                    models.CharField(default="Nigeria", max_length=250, null=True),
                ),
                ("postal_code", models.CharField(max_length=20, null=True)),
                ("address_line_1", models.CharField(max_length=250, null=True)),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=300, null=True)),
                ("profile_picture", models.ImageField(null=True, upload_to="")),
                ("first_name", models.CharField(max_length=250, null=True)),
                ("last_name", models.CharField(max_length=250, null=True)),
                ("email", models.EmailField(blank=True, max_length=250, null=True)),
                ("address_line_1", models.CharField(max_length=250, null=True)),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("city", models.CharField(max_length=250, null=True)),
                ("state", models.CharField(max_length=250, null=True)),
                ("country", models.CharField(default="Nigeria", max_length=250)),
                ("postal_code", models.PositiveIntegerField(null=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=250, null=True)),
                ("last_name", models.CharField(max_length=250, null=True)),
                ("email", models.EmailField(blank=True, max_length=250, null=True)),
                ("phone_number", models.PositiveIntegerField(null=True)),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_address",
                        to="customer.address",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customer.customer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customer",
            ),
        ),
    ]
