# Generated by Django 4.1.1 on 2022-09-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_alter_address_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(default="Nigeria", max_length=250, null=True),
        ),
    ]
