# Generated by Django 4.1.1 on 2022-09-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_alter_address_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeliveryAddress",
        ),
    ]
